{
 "bad": [
  "Proxy",
  "aio.TCP",
  "aio.socket_for_url",
  "callback",
  "callback.__name__",
  "common.log.exception",
  "corof",
  "create",
  "f",
  "open_connection",
  "sio.socket_for_url",
  "socket.IPPROTO_TCP",
  "socket.IP_TOS",
  "socket.SOL_IP",
  "socket.SOL_SOCKET",
  "socket.SOL_TCP",
  "socket.SO_KEEPALIVE",
  "socket.TCP_KEEPCNT",
  "socket.TCP_KEEPIDLE",
  "socket.TCP_KEEPINTVL",
  "socket.TCP_NODELAY",
  "socket.error",
  "sockio.__init__.CONCURRENCY_MAP"
 ],
 "deps": {
  "_asyncio": [
   "python/conda-forge/linux-64/python-3.8.5-h1103e12_6_cpython"
  ],
  "argparse": [
   "argparse/conda-forge/osx-64/argparse-1.4.0-py26_0",
   "python/conda-forge/linux-64/python-3.6.10-he5300dc_1011_cpython",
   "python/conda-forge/linux-64/python-3.8.5-h1103e12_6_cpython"
  ],
  "asyncio": [],
  "functools": [
   "python/conda-forge/linux-64/python-3.6.10-he5300dc_1011_cpython",
   "python/conda-forge/linux-64/python-3.8.5-h1103e12_6_cpython"
  ],
  "logging": [
   "python/conda-forge/linux-64/python-3.6.10-he5300dc_1011_cpython",
   "python/conda-forge/linux-64/python-3.8.5-h1103e12_6_cpython"
  ],
  "socket": [
   "python/conda-forge/linux-64/python-3.6.10-he5300dc_1011_cpython",
   "python/conda-forge/linux-64/python-3.8.5-h1103e12_6_cpython"
  ],
  "threading": [
   "python/conda-forge/linux-64/python-3.6.10-he5300dc_1011_cpython",
   "python/conda-forge/linux-64/python-3.8.5-h1103e12_6_cpython"
  ],
  "urllib": [
   "python/conda-forge/linux-64/python-3.6.10-he5300dc_1011_cpython",
   "python/conda-forge/linux-64/python-3.8.5-h1103e12_6_cpython"
  ]
 }
}