{
 "bad": [
  "DriveFile",
  "__future__.annotations",
  "drivelib.__init__.get_versions",
  "google.auth.exceptions.RefreshError",
  "google.auth.transport.requests.Request",
  "google.oauth2.credentials",
  "google_auth_oauthlib.flow.InstalledAppFlow.from_client_config",
  "hashlib.md5",
  "os.path.getsize",
  "os.remove"
 ],
 "deps": {
  "DriveFile": [],
  "__future__": [],
  "abc": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ],
  "drivelib": [],
  "google": [],
  "google_auth_httplib2": [
   "google-auth-httplib2/conda-forge/noarch/google-auth-httplib2-0.1.0-pyhd8ed1ab_0"
  ],
  "google_auth_oauthlib": [
   "google-auth-oauthlib/conda-forge/noarch/google-auth-oauthlib-0.4.4-pyhd8ed1ab_0"
  ],
  "googleapiclient": [
   "google-api-python-client/conda-forge/noarch/google-api-python-client-1.7.8-py_0"
  ],
  "hashlib": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ],
  "json": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ],
  "logging": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ],
  "oauth2client": [
   "oauth2client/conda-forge/noarch/oauth2client-4.1.3-py_0"
  ],
  "os": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ],
  "urllib": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ]
 }
}