{
 "bad": [
  "aiohttp",
  "aiohttp.ClientConnectionError",
  "aiohttp.ClientResponse",
  "aiohttp.ClientSession",
  "aiohttp.ClientTimeout",
  "asyncio",
  "asyncio.Queue",
  "asyncio.ensure_future",
  "asyncio.gather",
  "asyncio.new_event_loop",
  "asyncio.wait",
  "cgi",
  "cgi.parse_header",
  "collections.UserList",
  "collections.namedtuple",
  "concurrent.futures.ThreadPoolExecutor",
  "contextlib",
  "contextlib.contextmanager",
  "file_pb",
  "file_pb.close",
  "file_pb.update",
  "filepath_partial",
  "functools.partial",
  "get_file",
  "get_ipython",
  "ipykernel.zmqshell",
  "itertools.count",
  "object.__repr__",
  "os",
  "os.environ.get",
  "parfive.utils.get_ftp_size",
  "pkg_resources.DistributionNotFound",
  "pkg_resources.get_distribution",
  "pytest",
  "pytest.fixture",
  "pytest.mark.allow_hosts",
  "tqdm.notebook",
  "unittest.mock.patch",
  "urllib.parse"
 ],
 "deps": {
  "aioftp": [
   "aioftp/conda-forge/noarch/aioftp-0.17.0-py_0"
  ],
  "aiohttp": [],
  "asyncio": [],
  "cgi": [],
  "collections": [],
  "concurrent": [],
  "contextlib": [],
  "file_pb": [],
  "filepath_partial": [],
  "functools": [],
  "get_file": [],
  "get_ipython": [],
  "ipykernel": [],
  "itertools": [],
  "object": [],
  "os": [],
  "parfive": [],
  "pathlib": [
   "pathlib/conda-forge/noarch/pathlib-1.0.1-py_1"
  ],
  "pkg_resources": [],
  "pytest": [],
  "pytest_localserver": [
   "pytest-localserver/conda-forge/noarch/pytest-localserver-0.4.1-py_0"
  ],
  "tqdm": [
   "tqdm/conda-forge/noarch/tqdm-4.20.0-py_0"
  ],
  "unittest": [],
  "urllib": []
 }
}