{
 "bad": [
  "Exception",
  "IOError",
  "__name__",
  "binascii.a2b_hex",
  "binascii.b2a_hex",
  "bytes",
  "collections.abc.Iterable",
  "dict",
  "enumerate",
  "geomet.wkb.dumps",
  "geomet.wkb.loads",
  "geomet.wkt.dumps",
  "geomet.wkt.loads",
  "input",
  "int",
  "isinstance",
  "len",
  "list",
  "max",
  "round",
  "tuple",
  "zip"
 ],
 "deps": [
  [
   "geomet-0.2.1.post1-pyh9f0ad1d_0",
   "geomet-0.3.0-pyhd3deb0d_0"
  ]
 ]
}