{
 "bad": [
  "errno",
  "errno.EEXIST",
  "google.auth",
  "google.auth.exceptions",
  "google.auth.transport.requests",
  "google.oauth2.credentials",
  "google_auth_oauthlib.flow.InstalledAppFlow.from_client_config",
  "os.path.dirname",
  "os.path.exists",
  "os.path.expanduser",
  "os.path.join",
  "pydata_google_auth.__init__.versions"
 ],
 "deps": {
  "errno": [],
  "google": [],
  "google_auth_oauthlib": [
   "google-auth-oauthlib/conda-forge/noarch/google-auth-oauthlib-0.4.1-py_0",
   "google-auth-oauthlib/conda-forge/noarch/google-auth-oauthlib-0.4.3-pyhd8ed1ab_0",
   "google-auth-oauthlib/conda-forge/noarch/google-auth-oauthlib-0.4.4-pyhd8ed1ab_0"
  ],
  "json": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython",
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_2_cpython",
   "python/conda-forge/linux-64/python-3.6.7-h381d211_1004",
   "python/conda-forge/linux-64/python-3.7.10-hffdb5ce_100_cpython"
  ],
  "logging": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython",
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_2_cpython",
   "python/conda-forge/linux-64/python-3.6.7-h381d211_1004",
   "python/conda-forge/linux-64/python-3.7.10-hffdb5ce_100_cpython"
  ],
  "oauthlib": [
   "oauthlib/conda-forge/noarch/oauthlib-2.0.7-py_0",
   "oauthlib/conda-forge/noarch/oauthlib-3.0.1-py_0",
   "oauthlib/conda-forge/noarch/oauthlib-3.1.1-pyhd8ed1ab_0"
  ],
  "os": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython",
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_2_cpython",
   "python/conda-forge/linux-64/python-3.6.7-h381d211_1004",
   "python/conda-forge/linux-64/python-3.7.10-hffdb5ce_100_cpython"
  ],
  "pydata_google_auth": []
 }
}