{
 "bad": [
  "_version.get_versions",
  "errno.EEXIST",
  "google_auth_oauthlib.flow.InstalledAppFlow.from_client_config",
  "json.dump",
  "json.load",
  "json.loads",
  "logging.getLogger",
  "os.environ",
  "os.makedirs",
  "os.name",
  "os.path.dirname",
  "os.path.exists",
  "os.path.expanduser",
  "os.path.join",
  "pydata_google_auth._version.version_json",
  "pydata_google_auth.auth.CLIENT_ID",
  "pydata_google_auth.auth.CLIENT_SECRET",
  "pydata_google_auth.auth.get_application_default_credentials",
  "pydata_google_auth.auth.get_user_credentials",
  "pydata_google_auth.auth.logger",
  "pydata_google_auth.cache.CredentialsCache",
  "pydata_google_auth.cache.READ_WRITE",
  "pydata_google_auth.cache.ReadWriteCredentialsCache",
  "pydata_google_auth.cache.WriteOnlyCredentialsCache",
  "pydata_google_auth.cache._DIRNAME",
  "pydata_google_auth.cache._FILENAME",
  "pydata_google_auth.cache._get_default_credentials_path",
  "pydata_google_auth.cache._load_user_credentials_from_file",
  "pydata_google_auth.cache._load_user_credentials_from_info",
  "pydata_google_auth.cache._save_user_account_credentials",
  "pydata_google_auth.cache.logger",
  "pydata_google_auth.exceptions.PyDataCredentialsError",
  "pydata_google_auth.versions"
 ],
 "deps": {
  "_version": [],
  "errno": [],
  "google_auth_oauthlib": [],
  "json": [],
  "logging": [],
  "os": [],
  "pydata_google_auth": []
 }
}