{
 "bad": [
  "RuntimeError.__init__",
  "TomlError",
  "error",
  "flush",
  "format_rfc3339",
  "merge_tables",
  "object_pairs_hook",
  "parse_rfc3339_re",
  "process_value",
  "translate"
 ],
 "deps": [
  [
   "pathlib-1.0.1-py27_0",
   "pathlib-1.0.1-py27_1",
   "pathlib-1.0.1-py_1"
  ],
  [
   "pytoml-0.1.20-py_0",
   "pytoml-0.1.21-py_0"
  ]
 ]
}