{
 "bad": [
  "execnet.DataFormatError",
  "execnet.dumps",
  "execnet.loads",
  "py.io.TerminalWriter",
  "py.io.TextIO",
  "py.path.local",
  "pytest.mark.tryfirst"
 ],
 "deps": {
  "_pytest": [
   "pytest/conda-forge/linux-64/pytest-4.6.0-py37_0",
   "pytest/conda-forge/linux-64/pytest-4.6.3-py27_0",
   "pytest/conda-forge/linux-64/pytest-6.0.2-py36hc560c46_0",
   "pytest/conda-forge/linux-64/pytest-6.1.1-py37hc8dfbb8_0"
  ],
  "execnet": [],
  "pprint": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ],
  "py": [
   "py/conda-forge/noarch/py-1.8.2-pyh9f0ad1d_0"
  ],
  "pytest": [
   "pytest/conda-forge/linux-64/pytest-4.6.0-py37_0",
   "pytest/conda-forge/linux-64/pytest-4.6.3-py27_0",
   "pytest/conda-forge/linux-64/pytest-6.0.2-py36hc560c46_0",
   "pytest/conda-forge/linux-64/pytest-6.1.1-py37hc8dfbb8_0"
  ]
 }
}